# Site settings
title: hugo.sereno.ferreira
subtitle: "Hacking life, the binary way"
author: "Hugo Sereno Ferreira"
description: This is a blog about software, some mathematics, and the occasional philosophy. Not necessarily in that order
keywords: "Software Engineering Mathematics Philosophy."

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hugoferreira.github.io" # the base hostname & protocol for your site

twitter_username: ferreira_hugo
github_username: hugoferreira
linkedin_username: hugoserenoferreira
simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge

gems:
- jekyll-sitemap
